# Generated by Django 5.1.15 on 2026-04-22 06:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schools', '0012_campus'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('staff_role', models.CharField(choices=[('TEACHER', 'Teacher'), ('STAFF', 'Staff')], default='STAFF', max_length=20)),
                ('employee_id', models.CharField(blank=True, max_length=50)),
                ('designation', models.CharField(blank=True, max_length=120)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('joined_on', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_members', to='schools.school')),
            ],
            options={
                'ordering': ['full_name', 'id'],
                'constraints': [models.UniqueConstraint(fields=('school', 'employee_id'), name='uniq_employee_id_per_school')],
            },
        ),
    ]
