# Generated by Django 5.1.15 on 2026-04-21 16:32

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("frontoffice", "0001_initial"),
        ("students", "0008_student_slug"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="enquiry",
            name="converted_student",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="source_enquiries",
                to="students.student",
            ),
        ),
        migrations.CreateModel(
            name="EnquiryFollowUp",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("follow_up_on", models.DateField(default=django.utils.timezone.localdate)),
                (
                    "outcome",
                    models.CharField(
                        choices=[
                            ("NO_RESPONSE", "No Response"),
                            ("INTERESTED", "Interested"),
                            ("VISIT_SCHEDULED", "Visit Scheduled"),
                            ("CALL_BACK", "Call Back"),
                            ("NOT_INTERESTED", "Not Interested"),
                        ],
                        default="CALL_BACK",
                        max_length=30,
                    ),
                ),
                ("next_follow_up_date", models.DateField(blank=True, null=True)),
                ("summary", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="frontoffice_follow_ups",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "enquiry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="follow_ups",
                        to="frontoffice.enquiry",
                    ),
                ),
            ],
            options={
                "ordering": ["-follow_up_on", "-created_at"],
            },
        ),
    ]
