# Generated by Django 5.1.15 on 2026-04-25 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontoffice', '0004_calllog'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagedeliverylog',
            name='attempt_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='messagedeliverylog',
            name='delivered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='messagedeliverylog',
            name='last_attempt_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='messagedeliverylog',
            name='read_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
