# Generated by Django 6.0.4 on 2026-04-27 07:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("schools", "0019_school_cin_number_school_currency_school_gst_number_and_more"),
        ("students", "0019_phase2_student_ops_models"),
    ]

    operations = [
        migrations.CreateModel(
            name="Bed",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("bed_number", models.CharField(max_length=50)),
                ("is_occupied", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="Hostel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                (
                    "hostel_type",
                    models.CharField(
                        choices=[("BOYS", "Boys"), ("GIRLS", "Girls"), ("COED", "Co-Ed")],
                        default="BOYS",
                        max_length=10,
                    ),
                ),
                ("address", models.TextField(blank=True)),
                ("warden_name", models.CharField(blank=True, max_length=150)),
                ("warden_phone", models.CharField(blank=True, max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hostels",
                        to="schools.school",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MessPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("description", models.TextField(blank=True)),
                ("monthly_fee", models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mess_plans",
                        to="schools.school",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Room",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("room_number", models.CharField(max_length=50)),
                (
                    "room_type",
                    models.CharField(
                        blank=True, help_text="Example: AC, Non-AC, 4-Seater", max_length=100
                    ),
                ),
                ("capacity", models.PositiveIntegerField(default=4)),
                ("monthly_rent", models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "hostel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rooms",
                        to="hostel.hostel",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="HostelAllocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("allocated_on", models.DateField(auto_now_add=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "bed",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="allocations",
                        to="hostel.bed",
                    ),
                ),
                (
                    "hostel",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="allocations",
                        to="hostel.hostel",
                    ),
                ),
                (
                    "student",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hostel_allocation",
                        to="students.student",
                    ),
                ),
                (
                    "mess_plan",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="allocations",
                        to="hostel.messplan",
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="allocations",
                        to="hostel.room",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="bed",
            name="room",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="beds", to="hostel.room"
            ),
        ),
    ]
