# Generated by Django 5.1.15 on 2026-04-29 06:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("schools", "0020_seed_advanced_erp_features"),
        ("security_office", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="GatePass",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "pass_type",
                    models.CharField(
                        choices=[
                            ("STUDENT_EXIT", "Student Exit"),
                            ("VISITOR_EXIT", "Visitor Exit"),
                            ("ASSET_MOVEMENT", "Asset Movement"),
                        ],
                        default="VISITOR_EXIT",
                        max_length=30,
                    ),
                ),
                ("person_name", models.CharField(max_length=140)),
                ("reason", models.CharField(blank=True, max_length=255)),
                ("issued_at", models.DateTimeField()),
                ("valid_till", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ISSUED", "Issued"),
                            ("USED", "Used"),
                            ("EXPIRED", "Expired"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="ISSUED",
                        max_length=20,
                    ),
                ),
                ("issued_by", models.CharField(blank=True, max_length=120)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="gate_passes",
                        to="schools.school",
                    ),
                ),
            ],
            options={
                "ordering": ["-issued_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="GuardRoster",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("guard_name", models.CharField(max_length=140)),
                (
                    "shift",
                    models.CharField(
                        choices=[
                            ("MORNING", "Morning"),
                            ("EVENING", "Evening"),
                            ("NIGHT", "Night"),
                        ],
                        default="MORNING",
                        max_length=20,
                    ),
                ),
                ("area", models.CharField(blank=True, max_length=120)),
                ("duty_date", models.DateField()),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="guard_rosters",
                        to="schools.school",
                    ),
                ),
            ],
            options={
                "ordering": ["-duty_date", "-id"],
            },
        ),
        migrations.CreateModel(
            name="PatrolCheckpointLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("checkpoint_name", models.CharField(max_length=140)),
                ("guard_name", models.CharField(max_length=140)),
                ("logged_at", models.DateTimeField()),
                ("status_note", models.CharField(blank=True, max_length=255)),
                ("is_alert", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="patrol_logs",
                        to="schools.school",
                    ),
                ),
            ],
            options={
                "ordering": ["-logged_at", "-id"],
            },
        ),
    ]
