# Generated by GPT-5.2 on 2026-04-21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_userinvitation"),
    ]

    operations = [
        migrations.AddField(
            model_name="userinvitation",
            name="sent_to",
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name="userinvitation",
            name="sent_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="userinvitation",
            name="send_error",
            field=models.TextField(blank=True),
        ),
    ]
