# Generated by Django 5.1.15 on 2026-04-25 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_user_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('SUPER_ADMIN', 'Super Admin'), ('SCHOOL_OWNER', 'School Owner'), ('ADMIN', 'Admin'), ('PRINCIPAL', 'Principal'), ('VICE_PRINCIPAL', 'Vice Principal'), ('MANAGEMENT_TRUSTEE', 'Management / Trustee'), ('REPORT_VIEWER', 'Report Viewer (Read-only)'), ('ACADEMIC_COORDINATOR', 'Academic Coordinator'), ('EXAM_CONTROLLER', 'Exam Controller'), ('CLASS_TEACHER', 'Class Teacher / Class Incharge'), ('SUBJECT_TEACHER', 'Subject Teacher'), ('HOD', 'Head of Department (HOD)'), ('SUBSTITUTE_TEACHER', 'Substitute Teacher'), ('TUTOR_MENTOR', 'Tutor / Mentor'), ('TEACHER', 'Teacher'), ('STUDENT', 'Student'), ('PARENT', 'Parent / Guardian'), ('OFFICE_ADMIN', 'Office Admin'), ('RECEPTIONIST', 'Receptionist / Front Desk'), ('ADMISSION_COUNSELOR', 'Admission Counselor'), ('HR_MANAGER', 'HR Manager'), ('STAFF_COORDINATOR', 'Staff Coordinator'), ('ACCOUNTANT', 'Accountant'), ('FEE_MANAGER', 'Fee Manager'), ('BILLING_EXECUTIVE', 'Billing Executive'), ('AUDITOR', 'Auditor'), ('TRANSPORT_MANAGER', 'Transport Manager'), ('TRANSPORT_SUPERVISOR', 'Transport Supervisor'), ('DRIVER', 'Driver'), ('CONDUCTOR_ATTENDANT', 'Conductor / Attendant'), ('HOSTEL_MANAGER', 'Hostel Manager'), ('HOSTEL_WARDEN', 'Hostel Warden'), ('ASSISTANT_WARDEN', 'Assistant Warden'), ('MESS_MANAGER', 'Mess Manager'), ('LIBRARIAN', 'Librarian'), ('LAB_ASSISTANT', 'Lab Assistant'), ('SPORTS_COACH', 'Sports Coach'), ('INVENTORY_MANAGER', 'Inventory Manager / Store Keeper'), ('IT_ADMINISTRATOR', 'IT Administrator'), ('SYSTEM_OPERATOR', 'System Operator / Data Entry Operator'), ('ROLE_PERMISSION_MANAGER', 'Role & Permission Manager'), ('API_INTEGRATION_USER', 'API / Integration User'), ('NOTIFICATION_MANAGER', 'Notification Manager (SMS/Email/WhatsApp)'), ('SCHOOL_COUNSELOR', 'School Counselor'), ('EVENT_MANAGER', 'Event Manager'), ('COMPLIANCE_OFFICER', 'Compliance Officer'), ('SECURITY_OFFICER', 'Security Officer'), ('DIGITAL_MARKETING_MANAGER', 'Digital Marketing Manager'), ('ALUMNI_MANAGER', 'Alumni Manager'), ('PLACEMENT_COORDINATOR', 'Placement Coordinator'), ('RESEARCH_COORDINATOR', 'Research Coordinator')], max_length=40),
        ),
    ]
