from django.urls import path

from .views import (
    campus_create,
    campus_delete,
    campus_edit,
    campus_list,
    school_communication_settings,
    school_create,
    school_delete,
    school_detail,
    school_export_csv,
    school_export_excel,
    school_import,
    school_import_errors_csv,
    school_import_sample,
    school_implementation,
    school_list,
    school_profile,
    school_setup_checklist,
    school_team,
    school_team_invite,
    school_team_resend_invite,
    school_toggle_status,
    school_update,
)

urlpatterns = [
    path("", school_list, name="school-list"),
    path("profile/", school_profile, name="school-profile"),
    path("export/csv/", school_export_csv, name="school-export-csv"),
    path("export/excel/", school_export_excel, name="school-export-excel"),
    path("import/", school_import, name="school-import"),
    path("import/errors/", school_import_errors_csv, name="school-import-errors"),
    path("import/sample/<str:file_type>/", school_import_sample, name="school-import-sample"),
    path("create/", school_create, name="school-create"),
    path("<int:id>/", school_detail, name="school-detail"),
    path("<int:id>/implementation/", school_implementation, name="school-implementation"),
    path("<int:id>/status/", school_toggle_status, name="school-toggle-status"),
    path("<int:id>/campuses/", campus_list, name="campus-list"),
    path("<int:id>/campuses/create/", campus_create, name="campus-create"),
    path("<int:id>/campuses/<int:campus_id>/edit/", campus_edit, name="campus-edit"),
    path("<int:id>/campuses/<int:campus_id>/delete/", campus_delete, name="campus-delete"),
    path("<int:id>/setup/", school_setup_checklist, name="school-setup-checklist"),
    path("<int:id>/team/", school_team, name="school-team"),
    path("<int:id>/team/invite/", school_team_invite, name="school-team-invite"),
    path("<int:id>/team/invitations/<int:invitation_id>/resend/", school_team_resend_invite, name="school-team-invite-resend"),
    path("<int:id>/communication/", school_communication_settings, name="school-comm-settings-superadmin"),
    path("communication/", school_communication_settings, name="school-comm-settings"),
    path("edit/<int:id>/", school_update, name="school-edit"),
    path("delete/<int:id>/", school_delete, name="school-delete"),
]
