# Generated by Django 5.1.15 on 2026-04-29 04:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("digital_marketing", "0001_initial"),
        ("schools", "0020_seed_advanced_erp_features"),
    ]

    operations = [
        migrations.CreateModel(
            name="SEOTracker",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("page_url", models.URLField()),
                ("keyword", models.CharField(max_length=160)),
                ("ranking_position", models.PositiveIntegerField(default=0)),
                ("impressions", models.PositiveIntegerField(default=0)),
                ("clicks", models.PositiveIntegerField(default=0)),
                ("ctr_percent", models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ("audit_notes", models.TextField(blank=True)),
                ("tracked_on", models.DateField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="seo_trackers",
                        to="schools.school",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SocialAccountConnection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "platform",
                    models.CharField(
                        choices=[
                            ("INSTAGRAM", "Instagram"),
                            ("FACEBOOK", "Facebook"),
                            ("YOUTUBE", "YouTube"),
                            ("LINKEDIN", "LinkedIn"),
                            ("X", "X/Twitter"),
                        ],
                        max_length=20,
                    ),
                ),
                ("handle", models.CharField(max_length=120)),
                ("profile_url", models.URLField(blank=True)),
                ("access_token", models.CharField(blank=True, max_length=255)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="social_accounts",
                        to="schools.school",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SocialPost",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("title", models.CharField(max_length=180)),
                ("caption", models.TextField(blank=True)),
                ("scheduled_at", models.DateTimeField(blank=True, null=True)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("SCHEDULED", "Scheduled"),
                            ("PUBLISHED", "Published"),
                            ("FAILED", "Failed"),
                        ],
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
                ("reach", models.PositiveIntegerField(default=0)),
                ("clicks", models.PositiveIntegerField(default=0)),
                ("leads_generated", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "account",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="posts",
                        to="digital_marketing.socialaccountconnection",
                    ),
                ),
                (
                    "campaign",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="social_posts",
                        to="digital_marketing.marketingcampaign",
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="social_posts",
                        to="schools.school",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="WebsiteFormIntegration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=140)),
                ("website_url", models.URLField()),
                ("endpoint_url", models.URLField(blank=True)),
                ("auth_key", models.CharField(blank=True, max_length=255)),
                ("source_label", models.CharField(default="Website Form", max_length=80)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="website_integrations",
                        to="schools.school",
                    ),
                ),
            ],
        ),
    ]
