# Generated by Django 5.1.15 on 2026-04-29 05:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("digital_marketing", "0002_seotracker_socialaccountconnection_socialpost_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SocialConnectionTestLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "result",
                    models.CharField(
                        choices=[("SUCCESS", "Success"), ("FAILED", "Failed")], max_length=20
                    ),
                ),
                ("message", models.CharField(blank=True, max_length=255)),
                ("tested_at", models.DateTimeField(auto_now_add=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="test_logs",
                        to="digital_marketing.socialaccountconnection",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SocialPublishRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "result",
                    models.CharField(
                        choices=[("SUCCESS", "Success"), ("FAILED", "Failed"), ("RETRY", "Retry")],
                        max_length=20,
                    ),
                ),
                ("message", models.CharField(blank=True, max_length=255)),
                ("attempt_no", models.PositiveIntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="publish_runs",
                        to="digital_marketing.socialpost",
                    ),
                ),
            ],
        ),
    ]
