# Generated by Django 6.0.4 on 2026-04-20 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0003_studentpromotion_transfercertificate"),
    ]

    operations = [
        migrations.RenameField(
            model_name="student",
            old_name="address",
            new_name="current_address",
        ),
        migrations.AddField(
            model_name="student",
            name="blood_group",
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name="student",
            name="email",
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name="student",
            name="father_name",
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name="student",
            name="father_occupation",
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name="student",
            name="father_phone",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="student",
            name="guardian_occupation",
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name="student",
            name="mother_name",
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name="student",
            name="mother_occupation",
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name="student",
            name="mother_phone",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="student",
            name="permanent_address",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="student",
            name="relation_with_student",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="student",
            name="student_phone",
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
