# Generated by Django 6.0.4 on 2026-04-20 18:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("students", "0004_expand_student_admission_fields"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="aadhar_number",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="student",
            name="category",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="student",
            name="father_email",
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name="student",
            name="guardian_email",
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name="student",
            name="leaving_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="student",
            name="medical_conditions",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="student",
            name="middle_name",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="student",
            name="mother_email",
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name="student",
            name="mother_tongue",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="student",
            name="play_school_name",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="student",
            name="previous_school",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="student",
            name="religion",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="student",
            name="roll_number",
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name="student",
            name="blood_group",
            field=models.CharField(
                blank=True,
                choices=[
                    ("A+", "A+"),
                    ("A-", "A-"),
                    ("B+", "B+"),
                    ("B-", "B-"),
                    ("AB+", "AB+"),
                    ("AB-", "AB-"),
                    ("O+", "O+"),
                    ("O-", "O-"),
                ],
                max_length=10,
            ),
        ),
    ]
