# Generated by Django 6.0.4 on 2026-04-20 12:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("students", "0005_student_more_fields_and_monthly_admission"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="aadhar_card",
            field=models.FileField(blank=True, null=True, upload_to="students/documents/"),
        ),
        migrations.AddField(
            model_name="student",
            name="academic_year",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="student",
            name="admission_status",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="student",
            name="allergies",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="student",
            name="alternate_mobile",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="student",
            name="bank_account_number",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="student",
            name="birth_certificate",
            field=models.FileField(blank=True, null=True, upload_to="students/documents/"),
        ),
        migrations.AddField(
            model_name="student",
            name="bus_number",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="student",
            name="caste_certificate",
            field=models.FileField(blank=True, null=True, upload_to="students/documents/"),
        ),
        migrations.AddField(
            model_name="student",
            name="chronic_disease",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="student",
            name="current_address_line1",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="student",
            name="current_address_line2",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="student",
            name="current_city",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="student",
            name="current_pincode",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="student",
            name="current_state",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="student",
            name="disability",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="student",
            name="disability_details",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="student",
            name="doctor_name",
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name="student",
            name="driver_contact",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="student",
            name="emergency_contact",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="student",
            name="emergency_medical_notes",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="student",
            name="father_aadhar",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="student",
            name="father_income",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="student",
            name="fee_category",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="student",
            name="guardian_address",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="student",
            name="hostel_required",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="student",
            name="house",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="student",
            name="identification_mark_1",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="student",
            name="identification_mark_2",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="student",
            name="ifsc_code",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="student",
            name="income_certificate",
            field=models.FileField(blank=True, null=True, upload_to="students/documents/"),
        ),
        migrations.AddField(
            model_name="student",
            name="mess_plan",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="student",
            name="migration_certificate",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="student",
            name="mother_aadhar",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="student",
            name="mother_income",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="student",
            name="nationality",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="student",
            name="parent_password",
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name="student",
            name="parent_username",
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name="student",
            name="passport_photo",
            field=models.FileField(blank=True, null=True, upload_to="students/documents/"),
        ),
        migrations.AddField(
            model_name="student",
            name="pen_number",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="student",
            name="permanent_address_line1",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="student",
            name="permanent_address_line2",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="student",
            name="permanent_city",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="student",
            name="permanent_pincode",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="student",
            name="permanent_same_as_current",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="student",
            name="permanent_state",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="student",
            name="pickup_point",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="student",
            name="previous_class",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="student",
            name="previous_grade",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="student",
            name="previous_marksheet",
            field=models.FileField(blank=True, null=True, upload_to="students/documents/"),
        ),
        migrations.AddField(
            model_name="student",
            name="previous_percentage",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="student",
            name="room_number",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="student",
            name="route_number",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="student",
            name="samagra_id",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="student",
            name="scholarship",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="student",
            name="stream",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="student",
            name="student_password",
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name="student",
            name="student_username",
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name="student",
            name="subjects",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="student",
            name="transfer_certificate_file",
            field=models.FileField(blank=True, null=True, upload_to="students/documents/"),
        ),
        migrations.AddField(
            model_name="student",
            name="transfer_certificate_number",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="student",
            name="transport_required",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="student",
            name="udise_id",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="student",
            name="warden_name",
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
