# Generated by GPT-5.2 on 2026-04-22

from django.db import migrations


def _relation_code(raw_value: str) -> str:
    value = (raw_value or "").strip().lower()
    if value in {"father", "dad", "papa"}:
        return "FATHER"
    if value in {"mother", "mom", "mummy"}:
        return "MOTHER"
    if value in {"guardian"}:
        return "GUARDIAN"
    return "OTHER"


def backfill_guardians(apps, schema_editor):
    Student = apps.get_model("students", "Student")
    Guardian = apps.get_model("students", "Guardian")
    StudentGuardian = apps.get_model("students", "StudentGuardian")

    for student in Student.objects.select_related("school").all().iterator():
        name = (getattr(student, "guardian_name", "") or "").strip()
        if not name:
            continue

        phone = (getattr(student, "guardian_phone", "") or "").strip()
        email = (getattr(student, "guardian_email", "") or "").strip()
        occupation = (getattr(student, "guardian_occupation", "") or "").strip()
        address = (getattr(student, "guardian_address", "") or "").strip()

        guardian, _ = Guardian.objects.get_or_create(
            school_id=student.school_id,
            full_name=name,
            phone=phone,
            defaults={
                "email": email,
                "occupation": occupation,
                "address": address,
            },
        )

        relation_text = (getattr(student, "relation_with_student", "") or "").strip()
        StudentGuardian.objects.get_or_create(
            student_id=student.id,
            guardian_id=guardian.id,
            defaults={
                "relation": _relation_code(relation_text),
                "relation_text": relation_text,
                "is_primary": True,
            },
        )


def reverse_backfill_guardians(apps, schema_editor):
    StudentGuardian = apps.get_model("students", "StudentGuardian")
    StudentGuardian.objects.all().delete()
    Guardian = apps.get_model("students", "Guardian")
    Guardian.objects.all().delete()


class Migration(migrations.Migration):
    dependencies = [
        ("students", "0016_guardian_studentguardian"),
    ]

    operations = [
        migrations.RunPython(backfill_guardians, reverse_backfill_guardians),
    ]
