# Generated by GPT-5.2 on 2026-04-21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_platform_and_role_overrides"),
    ]

    operations = [
        migrations.CreateModel(
            name="RolePermissionsOverride",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("role", models.CharField(max_length=20, unique=True)),
                ("permissions", models.JSONField(default=list)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
