# Generated by Django 6.0.4 on 2026-04-24 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_audit_log_export'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlogexport',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
