# Generated by Django 5.1.15 on 2026-04-25 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_audit_log_export_immutable_copy_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rolepermissionsoverride',
            name='role',
            field=models.CharField(max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name='rolesectionsoverride',
            name='role',
            field=models.CharField(max_length=40, unique=True),
        ),
    ]
