# Generated by Django 5.1.15 on 2026-04-27 08:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0027_serviceconfiguration_systembackup"),
        ("schools", "0019_school_cin_number_school_currency_school_gst_number_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="rolepermissionsoverride",
            name="school",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="role_overrides",
                to="schools.school",
            ),
        ),
        migrations.AlterField(
            model_name="rolepermissionsoverride",
            name="role",
            field=models.CharField(max_length=40),
        ),
        migrations.AlterUniqueTogether(
            name="rolepermissionsoverride",
            unique_together={("school", "role")},
        ),
    ]
