# Generated by Django 5.1.15 on 2026-04-27 11:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("schools", "0019_school_cin_number_school_currency_school_gst_number_and_more"),
        ("staff", "0001_initial"),
        ("students", "0019_phase2_student_ops_models"),
    ]

    operations = [
        migrations.CreateModel(
            name="CareerEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("FAIR", "Career Fair"),
                            ("INFO_SESSION", "University Info Session"),
                            ("WORKSHOP", "Workshop"),
                            ("GUEST_LECTURE", "Guest Lecture"),
                        ],
                        default="INFO_SESSION",
                        max_length=20,
                    ),
                ),
                ("date", models.DateTimeField()),
                ("location", models.CharField(default="Main Hall", max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "organizer",
                    models.CharField(
                        blank=True, help_text="External university or agency name", max_length=255
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="schools.school"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CareerProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("interests", models.TextField(blank=True, help_text="Comma separated interests")),
                ("target_exams", models.TextField(blank=True, help_text="e.g. JEE, NEET, SAT")),
                ("preferred_courses", models.TextField(blank=True)),
                ("preferred_universities", models.TextField(blank=True)),
                ("notes", models.TextField(blank=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "student",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="career_profile",
                        to="students.student",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CounselingSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                (
                    "session_type",
                    models.CharField(
                        choices=[
                            ("ONE_ON_ONE", "1-on-1 Session"),
                            ("GROUP", "Group Workshop"),
                            ("PARENT_MEETING", "Parent Consultation"),
                        ],
                        default="ONE_ON_ONE",
                        max_length=20,
                    ),
                ),
                ("scheduled_at", models.DateTimeField()),
                ("duration_minutes", models.IntegerField(default=30)),
                ("summary", models.TextField(blank=True)),
                ("follow_up_required", models.BooleanField(default=False)),
                ("is_completed", models.BooleanField(default=False)),
                (
                    "counselor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conducted_sessions",
                        to="staff.staffmember",
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="schools.school"
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="counseling_sessions",
                        to="students.student",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="University",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("location", models.CharField(help_text="City, Country", max_length=255)),
                ("website", models.URLField(blank=True)),
                ("is_abroad", models.BooleanField(default=False)),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="schools.school"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Universities",
            },
        ),
        migrations.CreateModel(
            name="Application",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("course", models.CharField(max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PLANNED", "Planned"),
                            ("APPLIED", "Applied"),
                            ("ACCEPTED", "Accepted"),
                            ("REJECTED", "Rejected"),
                            ("WAITLISTED", "Waitlisted"),
                            ("ENROLLED", "Enrolled"),
                        ],
                        default="PLANNED",
                        max_length=20,
                    ),
                ),
                ("deadline", models.DateField(blank=True, null=True)),
                ("applied_on", models.DateField(blank=True, null=True)),
                ("result_on", models.DateField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="university_applications",
                        to="students.student",
                    ),
                ),
                (
                    "university",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="career_counseling.university",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EventRegistration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("attended", models.BooleanField(default=False)),
                ("registered_at", models.DateTimeField(auto_now_add=True)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="registrations",
                        to="career_counseling.careerevent",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="students.student"
                    ),
                ),
            ],
            options={
                "unique_together": {("event", "student")},
            },
        ),
    ]
