# Generated by Django 5.1.15 on 2026-04-27 12:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("career_counseling", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="counselingsession",
            name="feedback",
            field=models.TextField(
                blank=True, help_text="Student feedback or post-session evaluation"
            ),
        ),
        migrations.AddField(
            model_name="counselingsession",
            name="meeting_link",
            field=models.URLField(blank=True, help_text="Zoom/Meet link for online sessions"),
        ),
        migrations.AddField(
            model_name="counselingsession",
            name="mode",
            field=models.CharField(
                choices=[("OFFLINE", "In-Person"), ("ONLINE", "Online Meeting")],
                default="OFFLINE",
                max_length=20,
            ),
        ),
    ]
