# Generated by Django 6.0.4 on 2026-04-27 07:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("fees", "0001_initial"),
        ("schools", "0019_school_cin_number_school_currency_school_gst_number_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="feepayment",
            name="payment_mode",
            field=models.CharField(
                choices=[
                    ("CASH", "Cash"),
                    ("ONLINE", "Online (Payment Gateway)"),
                    ("UPI", "UPI / QR Code"),
                    ("CHEQUE", "Cheque"),
                    ("BANK_TRANSFER", "Bank Transfer / NEFT"),
                ],
                default="CASH",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="FeeDiscount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                (
                    "discount_type",
                    models.CharField(
                        choices=[("PERCENT", "Percentage"), ("FIXED", "Fixed Amount")],
                        default="FIXED",
                        max_length=20,
                    ),
                ),
                ("value", models.DecimalField(decimal_places=2, max_digits=10)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fee_discounts",
                        to="schools.school",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="FeeFine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("fine_amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("grace_period_days", models.PositiveIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fee_fines",
                        to="schools.school",
                    ),
                ),
            ],
        ),
    ]
