from django.urls import path

from .views import (
    enquiry_convert,
    enquiry_create_page,
    enquiry_delete,
    enquiry_detail,
    enquiry_edit,
    enquiry_follow_up_create,
    enquiry_list,
    enquiry_update,
    followup_list,
    frontoffice_overview,
    meeting_create,
    meeting_list,
    meeting_detail,
    meeting_edit,
    meeting_status_update,
    messages_home,
    template_list,
    template_create,
    template_edit,
    template_delete,
    campaign_list,
    campaign_create,
    campaign_detail,
    campaign_send,
    visitor_checkout,
    visitor_create_page,
    visitor_delete,
    visitor_detail,
    visitor_edit,
    visitor_list,
    document_reminders,
    call_list,
    call_create,
    call_detail,
    call_edit,
    call_delete,
    frontoffice_search,
    frontoffice_daily_report,
)


urlpatterns = [
    path("", frontoffice_overview, name="frontoffice-overview"),
    path("search/", frontoffice_search, name="frontoffice-search"),
    path("reports/daily/", frontoffice_daily_report, name="frontoffice-daily-report"),
    path("enquiries/", enquiry_list, name="frontoffice-enquiry-list"),
    path("enquiries/create/", enquiry_create_page, name="frontoffice-enquiry-create-page"),
    path("enquiries/<int:enquiry_id>/", enquiry_detail, name="frontoffice-enquiry-detail"),
    path("enquiries/<int:enquiry_id>/edit/", enquiry_edit, name="frontoffice-enquiry-edit"),
    path("enquiries/<int:enquiry_id>/delete/", enquiry_delete, name="frontoffice-enquiry-delete"),
    path("enquiries/<int:enquiry_id>/update/", enquiry_update, name="frontoffice-enquiry-update"),
    path("enquiries/<int:enquiry_id>/follow-ups/create/", enquiry_follow_up_create, name="frontoffice-enquiry-follow-up-create"),
    path("enquiries/<int:enquiry_id>/convert/", enquiry_convert, name="frontoffice-enquiry-convert"),
    path("follow-ups/", followup_list, name="frontoffice-followup-list"),
    path("meetings/", meeting_list, name="frontoffice-meeting-list"),
    path("meetings/create/", meeting_create, name="frontoffice-meeting-create"),
    path("meetings/<int:meeting_id>/", meeting_detail, name="frontoffice-meeting-detail"),
    path("meetings/<int:meeting_id>/edit/", meeting_edit, name="frontoffice-meeting-edit"),
    path("meetings/<int:meeting_id>/status/", meeting_status_update, name="frontoffice-meeting-status-update"),
    path("messages/", messages_home, name="frontoffice-messages-home"),
    path("messages/templates/", template_list, name="frontoffice-template-list"),
    path("messages/templates/create/", template_create, name="frontoffice-template-create"),
    path("messages/templates/<int:template_id>/edit/", template_edit, name="frontoffice-template-edit"),
    path("messages/templates/<int:template_id>/delete/", template_delete, name="frontoffice-template-delete"),
    path("messages/campaigns/", campaign_list, name="frontoffice-campaign-list"),
    path("messages/campaigns/create/", campaign_create, name="frontoffice-campaign-create"),
    path("messages/campaigns/<int:campaign_id>/", campaign_detail, name="frontoffice-campaign-detail"),
    path("messages/campaigns/<int:campaign_id>/send/", campaign_send, name="frontoffice-campaign-send"),
    path("document-reminders/", document_reminders, name="frontoffice-document-reminders"),
    path("calls/", call_list, name="frontoffice-call-list"),
    path("calls/create/", call_create, name="frontoffice-call-create"),
    path("calls/<int:call_id>/", call_detail, name="frontoffice-call-detail"),
    path("calls/<int:call_id>/edit/", call_edit, name="frontoffice-call-edit"),
    path("calls/<int:call_id>/delete/", call_delete, name="frontoffice-call-delete"),
    path("visitors/", visitor_list, name="frontoffice-visitor-list"),
    path("visitors/create/", visitor_create_page, name="frontoffice-visitor-create-page"),
    path("visitors/<int:visitor_id>/", visitor_detail, name="frontoffice-visitor-detail"),
    path("visitors/<int:visitor_id>/edit/", visitor_edit, name="frontoffice-visitor-edit"),
    path("visitors/<int:visitor_id>/delete/", visitor_delete, name="frontoffice-visitor-delete"),
    path("visitors/<int:visitor_id>/checkout/", visitor_checkout, name="frontoffice-visitor-checkout"),
]
