# Generated by Django 6.0.4 on 2026-04-20 20:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("academics", "0001_initial"),
        ("schools", "0003_school_student_capacity_school_allowed_campuses"),
        ("students", "0006_student_aadhar_card_student_academic_year_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Exam",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("exam_date", models.DateField()),
                ("total_marks", models.PositiveIntegerField(default=100)),
                ("passing_marks", models.PositiveIntegerField(default=33)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "academic_class",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exams",
                        to="academics.academicclass",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_exams",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exams",
                        to="schools.school",
                    ),
                ),
            ],
            options={
                "ordering": ["-exam_date", "name"],
                "unique_together": {("academic_class", "name", "exam_date")},
            },
        ),
        migrations.CreateModel(
            name="ExamMark",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("marks_obtained", models.DecimalField(decimal_places=2, max_digits=6)),
                ("remark", models.CharField(blank=True, max_length=255)),
                (
                    "exam",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="marks",
                        to="exams.exam",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exam_marks",
                        to="students.student",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="exam_marks",
                        to="academics.academicsubject",
                    ),
                ),
            ],
            options={
                "ordering": ["student__first_name", "subject__name"],
                "unique_together": {("exam", "student", "subject")},
            },
        ),
    ]
