# Generated by Django 6.0.4 on 2026-04-27 07:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("exams", "0001_initial"),
        ("schools", "0019_school_cin_number_school_currency_school_gst_number_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="exammark",
            name="grade",
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.CreateModel(
            name="GradeSystem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("min_percentage", models.DecimalField(decimal_places=2, max_digits=5)),
                ("max_percentage", models.DecimalField(decimal_places=2, max_digits=5)),
                ("grade_point", models.DecimalField(decimal_places=2, default=0, max_digits=4)),
                ("remark", models.CharField(blank=True, max_length=100)),
                (
                    "school",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="grade_systems",
                        to="schools.school",
                    ),
                ),
            ],
            options={
                "ordering": ["-min_percentage"],
                "unique_together": {("school", "name", "min_percentage")},
            },
        ),
    ]
