from django.urls import path

from .views import (
    student_admission_workflow,
    student_communication_logs,
    student_compliance,
    student_create,
    student_delete,
    student_delete_by_id,
    student_detail,
    student_detail_by_id,
    student_detail_pdf,
    student_detail_pdf_by_id,
    student_discipline,
    student_documents,
    student_documents_by_id,
    student_guardians,
    student_health,
    student_history_timeline,
    student_id_card_designer,
    student_id_cards_pdf,
    student_import,
    student_import_sample,
    student_list,
    student_promotion,
    student_promotion_by_id,
    student_tc_requests,
    student_transfer_certificate,
    student_transfer_certificate_by_id,
    student_transfer_certificate_pdf,
    student_transfer_certificate_pdf_by_id,
    student_update,
    student_update_by_id,
)

urlpatterns = [
    path("", student_list, name="student-list"),
    path("create/", student_create, name="student-create"),
    path("import/", student_import, name="student-import"),
    path("import/sample/<str:file_type>/", student_import_sample, name="student-import-sample"),
    path("id-cards/designer/", student_id_card_designer, name="student-id-card-designer"),
    path("id-cards/pdf/", student_id_cards_pdf, name="student-id-cards-pdf"),
    # Backward-compatible numeric routes -> slug redirects
    path("<int:id>/", student_detail_by_id, name="student-detail-by-id"),
    path("<int:id>/pdf/", student_detail_pdf_by_id, name="student-detail-pdf-by-id"),
    path("<int:id>/edit/", student_update_by_id, name="student-edit-by-id"),
    path("<int:id>/delete/", student_delete_by_id, name="student-delete-by-id"),
    path("<int:id>/documents/", student_documents_by_id, name="student-documents-by-id"),
    path("<int:id>/promotion/", student_promotion_by_id, name="student-promotion-by-id"),
    path("<int:id>/tc/", student_transfer_certificate_by_id, name="student-tc-by-id"),
    path("<int:id>/tc/pdf/", student_transfer_certificate_pdf_by_id, name="student-tc-pdf-by-id"),
    path("<slug:slug>/", student_detail, name="student-detail"),
    path("<slug:slug>/pdf/", student_detail_pdf, name="student-detail-pdf"),
    path("<slug:slug>/edit/", student_update, name="student-edit"),
    path("<slug:slug>/delete/", student_delete, name="student-delete"),
    path("<slug:slug>/documents/", student_documents, name="student-documents"),
    path("<slug:slug>/guardians/", student_guardians, name="student-guardians"),
    path("<slug:slug>/workflow/", student_admission_workflow, name="student-workflow"),
    path("<slug:slug>/history/", student_history_timeline, name="student-history"),
    path("<slug:slug>/discipline/", student_discipline, name="student-discipline"),
    path("<slug:slug>/health/", student_health, name="student-health"),
    path("<slug:slug>/compliance/", student_compliance, name="student-compliance"),
    path(
        "<slug:slug>/communication-logs/",
        student_communication_logs,
        name="student-communication-logs",
    ),
    path("<slug:slug>/promotion/", student_promotion, name="student-promotion"),
    path("<slug:slug>/tc/", student_transfer_certificate, name="student-tc"),
    path("<slug:slug>/tc/requests/", student_tc_requests, name="student-tc-requests"),
    path("<slug:slug>/tc/pdf/", student_transfer_certificate_pdf, name="student-tc-pdf"),
]
