# Generated by GPT-5.2 on 2026-04-21

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("schools", "0003_school_student_capacity_school_allowed_campuses"),
    ]

    operations = [
        migrations.CreateModel(
            name="SubscriptionPlan",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=150)),
                ("code", models.CharField(max_length=50, unique=True)),
                ("price_monthly", models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ("max_students", models.PositiveIntegerField(default=1000)),
                ("max_campuses", models.PositiveIntegerField(default=1)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={"ordering": ["name"]},
        ),
        migrations.CreateModel(
            name="SchoolSubscription",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("status", models.CharField(choices=[("TRIAL", "Trial"), ("ACTIVE", "Active"), ("PAST_DUE", "Past Due"), ("CANCELLED", "Cancelled")], default="TRIAL", max_length=20)),
                ("starts_on", models.DateField(default=django.utils.timezone.now)),
                ("ends_on", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("plan", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="subscriptions", to="schools.subscriptionplan")),
                ("school", models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name="subscription", to="schools.school")),
            ],
            options={"ordering": ["-created_at"]},
        ),
    ]

