# Generated by GPT-5.2 on 2026-04-21

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("schools", "0004_subscription_models"),
    ]

    operations = [
        migrations.CreateModel(
            name="SubscriptionInvoice",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("period_start", models.DateField()),
                ("period_end", models.DateField()),
                ("amount", models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ("due_date", models.DateField(blank=True, null=True)),
                ("status", models.CharField(choices=[("DRAFT", "Draft"), ("ISSUED", "Issued"), ("PAID", "Paid"), ("VOID", "Void")], default="DRAFT", max_length=20)),
                ("issued_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("plan", models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name="invoices", to="schools.subscriptionplan")),
                ("school", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="subscription_invoices", to="schools.school")),
            ],
            options={"ordering": ["-created_at"]},
        ),
        migrations.CreateModel(
            name="SubscriptionPayment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("amount", models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ("method", models.CharField(choices=[("CASH", "Cash"), ("BANK", "Bank Transfer"), ("UPI", "UPI"), ("CARD", "Card"), ("OTHER", "Other")], default="BANK", max_length=20)),
                ("transaction_ref", models.CharField(blank=True, max_length=120)),
                ("paid_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("invoice", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="payments", to="schools.subscriptioninvoice")),
            ],
            options={"ordering": ["-paid_at", "-created_at"]},
        ),
    ]

