# Generated by GPT-5.2 on 2026-04-21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schools", "0005_subscription_billing_records"),
    ]

    operations = [
        migrations.CreateModel(
            name="PlanFeature",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=150)),
                ("code", models.CharField(max_length=80, unique=True)),
                ("description", models.CharField(blank=True, max_length=255)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={"ordering": ["name"]},
        ),
        migrations.AddField(
            model_name="subscriptionplan",
            name="features",
            field=models.ManyToManyField(blank=True, related_name="plans", to="schools.planfeature"),
        ),
    ]

