# Generated by GPT-5.2 on 2026-04-21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schools", "0006_plan_features"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscriptionplan",
            name="tier",
            field=models.CharField(choices=[("SILVER", "Silver"), ("GOLD", "Gold"), ("PLATINUM", "Platinum")], default="SILVER", max_length=20),
        ),
        migrations.AddField(
            model_name="subscriptionplan",
            name="billing_mode",
            field=models.CharField(choices=[("FLAT", "Flat monthly"), ("PER_STUDENT", "Per student"), ("PER_500", "Per 500 students")], default="FLAT", max_length=20),
        ),
        migrations.AddField(
            model_name="subscriptionplan",
            name="unit_price",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]

