# Generated by GPT-5.2 on 2026-04-21

from django.db import migrations

DEFAULT_FEATURES = [
    ("Students", "STUDENTS", "Student admission, profiles, documents, ID cards"),
    ("Academics", "ACADEMICS", "Classes, sections, subjects, syllabus"),
    ("Attendance", "ATTENDANCE", "Student & teacher attendance workflows"),
    ("Fees", "FEES", "Fee structure, ledger, payments, receipts"),
    ("Exams", "EXAMS", "Exam setup, marks entry, report cards"),
    ("Communication", "COMMUNICATION", "Notices and notifications"),
    ("Reports", "REPORTS", "Operational reports overview"),
]


def seed_features(apps, schema_editor):
    PlanFeature = apps.get_model("schools", "PlanFeature")
    for name, code, desc in DEFAULT_FEATURES:
        PlanFeature.objects.update_or_create(
            code=code,
            defaults={"name": name, "description": desc, "is_active": True},
        )


class Migration(migrations.Migration):
    dependencies = [
        ("schools", "0007_plan_tier_and_pricing"),
    ]

    operations = [
        migrations.RunPython(seed_features, migrations.RunPython.noop),
    ]
