# Generated by GPT-5.2 on 2026-04-21

from django.db import migrations


def seed_plans(apps, schema_editor):
    Plan = apps.get_model("schools", "SubscriptionPlan")
    Feature = apps.get_model("schools", "PlanFeature")

    features = {f.code: f for f in Feature.objects.all()}

    def upsert_plan(code, defaults, feature_codes):
        plan, _ = Plan.objects.update_or_create(code=code, defaults=defaults)
        selected = [features[c].id for c in feature_codes if c in features]
        if selected:
            plan.features.set(selected)
        return plan

    upsert_plan(
        "SILVER",
        {
            "name": "Silver",
            "tier": "SILVER",
            "billing_mode": "PER_500",
            "unit_price": 500,
            "price_monthly": 0,
            "max_students": 1000,
            "max_campuses": 1,
            "is_active": True,
        },
        ["STUDENTS", "ACADEMICS", "ATTENDANCE", "COMMUNICATION"],
    )

    upsert_plan(
        "GOLD",
        {
            "name": "Gold",
            "tier": "GOLD",
            "billing_mode": "PER_500",
            "unit_price": 750,
            "price_monthly": 0,
            "max_students": 1000,
            "max_campuses": 3,
            "is_active": True,
        },
        ["STUDENTS", "ACADEMICS", "ATTENDANCE", "FEES", "EXAMS", "COMMUNICATION"],
    )

    upsert_plan(
        "PLATINUM",
        {
            "name": "Platinum",
            "tier": "PLATINUM",
            "billing_mode": "PER_500",
            "unit_price": 1000,
            "price_monthly": 0,
            "max_students": 1000,
            "max_campuses": 5,
            "is_active": True,
        },
        ["STUDENTS", "ACADEMICS", "ATTENDANCE", "FEES", "EXAMS", "COMMUNICATION", "REPORTS"],
    )


class Migration(migrations.Migration):
    dependencies = [
        ("schools", "0008_seed_default_features"),
    ]

    operations = [
        migrations.RunPython(seed_plans, migrations.RunPython.noop),
    ]
