# Generated by Django 6.0.4 on 2026-04-24 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0017_more_plan_features_and_gating'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscriptioninvoice',
            options={'ordering': ['-created_at', '-id']},
        ),
        migrations.AlterField(
            model_name='implementationproject',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='implementationtask',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
