# Generated by Django 6.0.4 on 2026-04-27 07:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("schools", "0018_alter_subscriptioninvoice_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="school",
            name="cin_number",
            field=models.CharField(
                blank=True, help_text="Corporate Identification Number if applicable", max_length=30
            ),
        ),
        migrations.AddField(
            model_name="school",
            name="currency",
            field=models.CharField(default="INR", max_length=10),
        ),
        migrations.AddField(
            model_name="school",
            name="gst_number",
            field=models.CharField(blank=True, help_text="GSTIN for Indian schools", max_length=20),
        ),
        migrations.AddField(
            model_name="school",
            name="registration_number",
            field=models.CharField(
                blank=True, help_text="Official school registration number", max_length=100
            ),
        ),
        migrations.AddField(
            model_name="school",
            name="timezone",
            field=models.CharField(default="Asia/Kolkata", max_length=50),
        ),
        migrations.AddField(
            model_name="school",
            name="upi_id",
            field=models.CharField(
                blank=True, help_text="UPI ID for fee collection (e.g., school@upi)", max_length=100
            ),
        ),
    ]
