# Generated by Django 5.1.15 on 2026-04-27 11:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("research", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="grant",
            old_name="received_at",
            new_name="created_at",
        ),
        migrations.RemoveField(
            model_name="grant",
            name="source",
        ),
        migrations.AddField(
            model_name="grant",
            name="agency",
            field=models.CharField(default="N/A", max_length=255, verbose_name="Funding Agency"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="grant",
            name="grant_id",
            field=models.CharField(blank=True, max_length=100, verbose_name="Grant ID/Reference"),
        ),
        migrations.AddField(
            model_name="grant",
            name="received_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="grant",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="grant",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("APPROVED", "Approved"),
                    ("REJECTED", "Rejected"),
                    ("DISBURSED", "Disbursed"),
                ],
                default="PENDING",
                max_length=20,
            ),
        ),
    ]
